In [1]:
import pandas as pd

In [ ]:
import pandas as pd
#산지니로 예제 만들어보기
# 1) 예시 데이터 만들기(보통은 CSV/DB에서 읽어오지만, 여기선 바로 생성)
data = [
    {"date": "2026-05-01", "store": "Seoul",  "category": "Coffee", "units": 12, "unit_price": 4.5},
    {"date": "2026-05-01", "store": "Seoul",  "category": "Tea",    "units":  8, "unit_price": 3.8},
    {"date": "2026-05-01", "store": "Busan",  "category": "Coffee", "units": 10, "unit_price": 4.3},
    {"date": "2026-05-02", "store": "Seoul",  "category": "Coffee", "units": 15, "unit_price": 4.6},
    {"date": "2026-05-02", "store": "Busan",  "category": "Tea",    "units":  7, "unit_price": 3.7},
    {"date": "2026-05-03", "store": "Busan",  "category": "Coffee", "units":  9, "unit_price": 4.4},
]

df = pd.DataFrame(data)

# 2) 타입 변환(날짜 문자열 -> datetime)
df["date"] = pd.to_datetime(df["date"])

# 3) 파생 컬럼 만들기 (매출 = 수량 * 단가)
df["revenue"] = df["units"] * df["unit_price"]

print("=== 원본 데이터 ===")
print(df)

# 4) 필터링: 서울 매장 + 커피만
seoul_coffee = df[(df["store"] == "Seoul") & (df["category"] == "Coffee")]
print("\n=== 필터링(Seoul & Coffee) ===")
print(seoul_coffee)

# 5) 그룹 집계: 매장/카테고리별 총 판매수량, 총매출, 평균단가
summary = (
    df.groupby(["store", "category"])
      .agg(total_units=("units", "sum"),
           total_revenue=("revenue", "sum"),
           avg_unit_price=("unit_price", "mean"))
      .reset_index()
      .sort_values("total_revenue", ascending=False)
)

print("\n=== 그룹 집계 결과(store, category) ===")
print(summary)

# 6) 피벗 테이블: 날짜별 매장 총매출(가로로 펼치기)
pivot = df.pivot_table(
    index="date",
    columns="store",
    values="revenue",
    aggfunc="sum",
    fill_value=0
)

print("\n=== 피벗(날짜별 매장 매출) ===")
print(pivot)

# 7) 결측치 처리 맛보기: 일부 값을 NaN으로 만들고 채우기
df2 = df.copy()
df2.loc[0, "unit_price"] = None

print("\n=== 결측치 포함 ===")
print(df2[["date", "store", "category", "units", "unit_price", "revenue"]])

# unit_price 결측치를 매장별 평균 단가로 채우기
df2["unit_price"] = df2["unit_price"].fillna(df2.groupby("store")["unit_price"].transform("mean"))
df2["revenue"] = df2["units"] * df2["unit_price"]

print("\n=== 결측치 처리 후(매장별 평균으로 채움) ===")
print(df2[["date", "store", "category", "units", "unit_price", "revenue"]])

In [8]:
import pandas as pd

df = pd.DataFrame({
    "name":  ["Kim", "Lee", "Park"],
    "age":   [20, 21, 19],
    "score": [88, 92, 75]
})

df

   name  age  score
0   Kim   20     88
1   Lee   21     92
2  Park   19     75

In [4]:
  iris_df =pd.read_csv('Iris.csv')

In [5]:
iris_df

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [7]:
iris_df.shape # iris 의 형태를 로우,콜론 형태로 나타냄 = 크기

(150, 6)

In [9]:
iris_df.index
#괄호가 없는 명령어 index, shape 등 -> 속성
#괄호 있는 명령어 head emd -> 메소드

RangeIndex(start=0, stop=150, step=1)

In [10]:
iris_df.dtypes

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object

In [11]:
iris_df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [12]:
iris_df.tail()

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

In [13]:
iris_df.info()  #출력시 나오는 nonCount ->. 결측치 개수

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             150 non-null    int64
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB

In [15]:
iris_df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [19]:
iris_df[['SepalLengthCm','SepalWidthCm']]

KeyError: ('SepalLengthCm', 'SepalWidthCm')

In [21]:
setosa_df = iris_df[iris_df['Species'] == 'Iris-setosa']

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0    1            5.1           3.5            1.4           0.2  Iris-setosa
1    2            4.9           3.0            1.4           0.2  Iris-setosa
2    3            4.7           3.2            1.3           0.2  Iris-setosa
3    4            4.6           3.1            1.5           0.2  Iris-setosa
4    5            5.0           3.6            1.4           0.2  Iris-setosa
5    6            5.4           3.9            1.7           0.4  Iris-setosa
6    7            4.6           3.4            1.4           0.3  Iris-setosa
7    8            5.0           3.4            1.5           0.2  Iris-setosa
8    9            4.4           2.9            1.4           0.2  Iris-setosa
9   10            4.9           3.1            1.5           0.1  Iris-setosa
10  11            5.4           3.7            1.5           0.2  Iris-setosa
11  12            4.8           3.4            1.6           0.2  Iris-setosa
12  13            4.8           3.0            1.4           0.1  Iris-setosa
13  14            4.3           3.0            1.1           0.1  Iris-setosa
14  15            5.8           4.0            1.2           0.2  Iris-setosa
15  16            5.7           4.4            1.5           0.4  Iris-setosa
16  17            5.4           3.9            1.3           0.4  Iris-setosa
17  18            5.1           3.5            1.4           0.3  Iris-setosa
18  19            5.7           3.8            1.7           0.3  Iris-setosa
19  20            5.1           3.8            1.5           0.3  Iris-setosa
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa
40  41            5.0           3.5            1.3           0.3  Iris-setosa
41  42            4.5           2.3            1.3           0.3  Iris-setosa
42  43            4.4           3.2            1.3           0.2  Iris-setosa
43  44            5.0           3.5            1.6           0.6  Iris-setosa
44  45            5.1           3.8            1.9           0.4  Iris-setosa
45  46            4.8           3.0            1.4           0.3  Iris-setosa
46  47            5.1           3.8            1.6           0.2  Iris-setosa
47  48            4.6           3.2            1.4           0.2  Iris-setosa
48  49            5.3           3.7            1.5           0.2  Iris-setosa
49  50            5.0           3.3            1.4           0.2  Iris-setosa